# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Squad < Formula
  desc "Project-management framework for software work done with AI coding agents"
  homepage "https://github.com/zsiec/squad"
  version "0.3.0-rc1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zsiec/squad/releases/download/v0.3.0-rc1/squad_0.3.0-rc1_darwin_amd64.tar.gz"
      sha256 "2b0e67bab5145097ff7cba16944c1c3b04b830ccb969a8f60dc6c69e2eb2077c"

      define_method(:install) do
        bin.install "squad"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zsiec/squad/releases/download/v0.3.0-rc1/squad_0.3.0-rc1_darwin_arm64.tar.gz"
      sha256 "0929e3009f4fc07d17b7abd40bf986e4bdf1545d4849b39d9eb36aed3f3751bd"

      define_method(:install) do
        bin.install "squad"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zsiec/squad/releases/download/v0.3.0-rc1/squad_0.3.0-rc1_linux_amd64.tar.gz"
      sha256 "1c93a2a5ce6094dd0d57f3df2667071b85d6f4a896bce6c7c73c704e435c6123"
      define_method(:install) do
        bin.install "squad"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zsiec/squad/releases/download/v0.3.0-rc1/squad_0.3.0-rc1_linux_arm64.tar.gz"
      sha256 "ee37956e0610c5b3291037f713b3057646ed2a7bd0a4b33fe5f8bc4e182bcac6"
      define_method(:install) do
        bin.install "squad"
      end
    end
  end

  test do
    system "#{bin}/squad", "version"
  end
end
