# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Squad < Formula
  desc "Project-management framework for software work done with AI coding agents"
  homepage "https://github.com/zsiec/squad"
  version "0.3.0-rc3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zsiec/squad/releases/download/v0.3.0-rc3/squad_0.3.0-rc3_darwin_amd64.tar.gz"
      sha256 "e940d9547744204c374243d235c923ebb9b217708bc50b48739959b297f01eba"

      define_method(:install) do
        bin.install "squad"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zsiec/squad/releases/download/v0.3.0-rc3/squad_0.3.0-rc3_darwin_arm64.tar.gz"
      sha256 "7c29f38129370c52d3625939d53ba2e9f771b873e925c262eb0487dc1c7318c9"

      define_method(:install) do
        bin.install "squad"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zsiec/squad/releases/download/v0.3.0-rc3/squad_0.3.0-rc3_linux_amd64.tar.gz"
      sha256 "1ea1a98b57b5fdd9e1b1f2aa7d77d227df49f06320eb52569b66c64be93a1f38"
      define_method(:install) do
        bin.install "squad"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zsiec/squad/releases/download/v0.3.0-rc3/squad_0.3.0-rc3_linux_arm64.tar.gz"
      sha256 "a8b8fffdc616ab386eb8d5297b91dbf737f3fd9b72ae6ba6c359c6d3f4b5ec4e"
      define_method(:install) do
        bin.install "squad"
      end
    end
  end

  test do
    system "#{bin}/squad", "version"
  end
end
