# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Squad < Formula
  desc "Project-management framework for software work done with AI coding agents"
  homepage "https://github.com/zsiec/squad"
  version "0.3.0-rc4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zsiec/squad/releases/download/v0.3.0-rc4/squad_0.3.0-rc4_darwin_amd64.tar.gz"
      sha256 "9144ec96fbd7c431ad92b08c4e21860582aab87079a1f2ce76c0d014d66f9575"

      define_method(:install) do
        bin.install "squad"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zsiec/squad/releases/download/v0.3.0-rc4/squad_0.3.0-rc4_darwin_arm64.tar.gz"
      sha256 "bb974641c1d5e2f906ad0a0fd5e8e6754b895d430928b4e1c5c6fdeb4072420c"

      define_method(:install) do
        bin.install "squad"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zsiec/squad/releases/download/v0.3.0-rc4/squad_0.3.0-rc4_linux_amd64.tar.gz"
      sha256 "d097656fc8dc53c5f79e90a90b3192215276937079b94eebf4e447b56ef82ecc"
      define_method(:install) do
        bin.install "squad"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zsiec/squad/releases/download/v0.3.0-rc4/squad_0.3.0-rc4_linux_arm64.tar.gz"
      sha256 "08702836712ad5ccd4c975ef2db9e4ada6c1c2e3058d12b387ce573b987d6b2e"
      define_method(:install) do
        bin.install "squad"
      end
    end
  end

  test do
    system "#{bin}/squad", "version"
  end
end
