# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Squad < Formula
  desc "Project-management framework for software work done with AI coding agents"
  homepage "https://github.com/zsiec/squad"
  version "0.3.0-rc2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zsiec/squad/releases/download/v0.3.0-rc2/squad_0.3.0-rc2_darwin_amd64.tar.gz"
      sha256 "32c6336eb38564d42ffeda34ef305a22620c6f9febbec74e15782ef4b34b1078"

      define_method(:install) do
        bin.install "squad"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zsiec/squad/releases/download/v0.3.0-rc2/squad_0.3.0-rc2_darwin_arm64.tar.gz"
      sha256 "58d928b94ae6d15755392fe61998e54314116d9f1c44cd3d53b7b1a8253f205c"

      define_method(:install) do
        bin.install "squad"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zsiec/squad/releases/download/v0.3.0-rc2/squad_0.3.0-rc2_linux_amd64.tar.gz"
      sha256 "6882ca106254c2506b1862eea08c847bef6d3b7b51d55966bcc6ae994bcbef56"
      define_method(:install) do
        bin.install "squad"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zsiec/squad/releases/download/v0.3.0-rc2/squad_0.3.0-rc2_linux_arm64.tar.gz"
      sha256 "4eafa259bffb4323e825df144137c2617a7d646a466150d869e06b632c570f29"
      define_method(:install) do
        bin.install "squad"
      end
    end
  end

  test do
    system "#{bin}/squad", "version"
  end
end
